import { SignalType } from '../types';

export const SIGNAL_WEIGHTS: Record<SignalType, number> = {
  long_duration:           15,
  new_nationality:         15,
  high_amount:             20,
  property_cap_breach:     20,
  velocity_spike:          25,
  off_hours:               15,
  low_star_mismatch:       15,
  new_geo:                 10,
  new_agent:               25,
  cancel_ratio:            15,
  account_change:          15,
  lead_time_anomaly:       10,
  repeat_guest:            15,
  blacklist_match:         40,
  fake_name_detected:      25,
  disposable_email:        30,
  data_quality_low:        15,
  group_size_anomaly:      20,
  frequent_edits:          20,
  sub_agent_anomaly:       20,
  concurrent_sessions:     20,
  ip_reputation:           30,
  account_farming:         25,
  rapid_ip_switch:         30,
  failed_booking_attempts: 25,
  failed_payment_attempts: 30,
  chargeback_history:      25,
  credit_limit_risk:       30,
  high_risk_nationality:   15,
  doc_requirement_missing: 20,
  duplicate_passenger:     25,
};